// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>
namespace Constants
{
    public static class Models
    {

        // --- Ungrouped ---
        public const string CursorService = "CMS/CursorService";
        public const string ExampleGameplayServiceSettings = "CMS/ExampleGameplayServiceSettings";
        public const string MusicService = "CMS/MusicService";
        public const string Particles = "CMS/Prefabs/Particles";
    }
}
