// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>
namespace Constants
{
    public static class Models
    {

        // --- Ungrouped ---
        public const string ExampleGameplayServiceSettings = "CMS/ExampleGameplayServiceSettings";
    }
}
